### ISSUE TITLE
Disable the Clipboard Icon when there is no generated password for UX

### ISSUE THREAD

**Issue by DavidKozdra** [0ME9A/password#18]
![image](https://github.com/0ME9A/password/assets/45106564/43fe01da-a7d6-48fa-a2f0-c6760b13fa03)

The clipboard should not be clickable and should not become green on click 

add disabled attribute to the icon conditionally until the password var is set to some thing

**Comment by 0ME9A** [comment]
Thanks for the feedback, @DavidKozdra ! 🙌

I'll address the clipboard icon behaviour by adding the `disabled` attribute conditionally until the password variable is set to something. This should prevent the icon from being clickable and avoid the green highlight on click.

If you're interested in contributing or have any specific suggestions on how to implement this, feel free to jump in! Your input is valuable, and contributions are always welcome.

I'll work on this, but if you'd like to take a stab at it or collaborate, please let me know. Looking forward to your thoughts!

Thanks again for your help!

**Comment by DavidKozdra** [comment]
I will work on it pushing now

**Comment by DavidKozdra** [comment]
I'll need permission but the code is just this 
      <IconButton
              disabled={!history[0]?.password}
              onClick={handleCopy}
              title={`${isCopy ? "Copied" : "Copy"}`}
              sx={{
                p: ".5",
                m: 0,
                minWidth: "0",
                borderRadius: 2,
                color: `${isCopy ? "green" : ""}`,
                display: "flex",
                alignItems: "center",
              }}
            >
            
            in the Password Generator component

**Comment by 0ME9A** [comment]
Hi @DavidKozdra,

I appreciate your willingness to work on the clipboard icon issue. I've invited you to collaborate on the repository. Feel free to proceed with the changes, and if you have any questions or need assistance, don't hesitate to ask.

Looking forward to your contributions!

Best regards,
@0ME9A
